import React from 'react'

export const styles: Record<string, React.CSSProperties> = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    fontFamily: 'var(--vscode-font-family)',
    fontSize: 'var(--vscode-font-size)',
    color: 'var(--vscode-foreground)',
    background: 'var(--vscode-sideBar-background)',
  },
  messages: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px 8px',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flex: 1,
    opacity: 0.4,
    fontSize: 12,
    userSelect: 'none',
    paddingTop: 40,
  },
  emptyIcon: {
    fontSize: 24,
    opacity: 0.6,
  },
  emptyHint: {
    fontSize: 10,
    opacity: 0.7,
  },
  bubble: {
    borderRadius: 8,
    padding: '6px 10px',
    maxWidth: '92%',
    wordBreak: 'break-word',
    lineHeight: 1.5,
  },
  user: {
    alignSelf: 'flex-end',
    background: 'var(--vscode-button-background)',
    color: 'var(--vscode-button-foreground)',
  },
  assistant: {
    alignSelf: 'flex-start',
    background: 'var(--vscode-editor-inactiveSelectionBackground)',
  },
  telegramUser: {
    background: 'var(--vscode-activityBarBadge-background)',
    color: 'var(--vscode-activityBarBadge-foreground)',
  },
  telegramBadge: {
    fontSize: '10px',
    opacity: 0.7,
    marginBottom: 2,
  },
  streaming: {
    opacity: 0.9,
  },
  cursor: {
    animation: 'none',
    opacity: 0.7,
    marginLeft: 1,
  },
  inputRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    padding: 8,
    borderTop: '1px solid var(--vscode-panel-border)',
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 4,
  },
  toolRow: {
    display: 'flex',
    gap: 4,
    alignItems: 'center',
  },
  textareaRow: {
    display: 'flex',
    gap: 6,
    alignItems: 'flex-end',
  },
  textarea: {
    flex: 1,
    minWidth: 0,
    background: 'var(--vscode-input-background)',
    color: 'var(--vscode-input-foreground)',
    border: '1px solid var(--vscode-input-border)',
    borderRadius: 4,
    padding: 6,
    resize: 'none',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    boxSizing: 'border-box',
    minHeight: 48,
    maxHeight: 160,
    lineHeight: '1.5',
    overflowY: 'hidden',
  },
  sendButton: {
    flexShrink: 0,
    alignSelf: 'flex-end',
    background: '#0ea5e9',
    color: '#ffffff',
    border: 'none',
    borderRadius: 4,
    padding: '6px 14px',
    cursor: 'pointer',
  },
  stopButton: {
    flexShrink: 0,
    alignSelf: 'flex-end',
    background: '#ef4444',
    color: '#ffffff',
    border: 'none',
    borderRadius: 4,
    padding: '6px 12px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  iconButton: {
    flexShrink: 0,
    background: 'var(--vscode-button-secondaryBackground)',
    color: 'var(--vscode-button-secondaryForeground)',
    border: 'none',
    borderRadius: 4,
    padding: '3px 8px',
    cursor: 'pointer',
    fontSize: 13,
  },
  promptSelect: {
    flex: 1,
    minWidth: 0,
    background: 'var(--vscode-input-background)',
    color: 'var(--vscode-input-foreground)',
    border: '1px solid var(--vscode-input-border)',
    borderRadius: 3,
    padding: '3px 4px',
    fontSize: 11,
    cursor: 'pointer',
  },
  quickRunButton: {
    flexShrink: 0,
    background: '#0ea5e9',
    color: '#fff',
    border: 'none',
    borderRadius: 3,
    padding: '3px 7px',
    fontSize: 13,
    cursor: 'pointer',
    lineHeight: 1,
  },
  previewButton: {
    flexShrink: 0,
    background: '#0ea5e9',
    color: '#fff',
    border: 'none',
    borderRadius: 4,
    padding: '3px 8px',
    fontSize: 14,
    cursor: 'pointer',
    lineHeight: 1,
  },
  rowLabel: {
    flexShrink: 0,
    fontSize: 10,
    opacity: 0.5,
    userSelect: 'none' as const,
    letterSpacing: '0.03em',
  },
  runButton: {
    flexShrink: 0,
    background: '#22c55e',
    color: '#fff',
    border: 'none',
    borderRadius: 3,
    padding: '3px 7px',
    fontSize: 13,
    cursor: 'pointer',
    lineHeight: 1,
  },
  gitBtn: {
    flexShrink: 0,
    background: 'var(--vscode-button-secondaryBackground)',
    color: 'var(--vscode-button-secondaryForeground)',
    border: 'none',
    borderRadius: 3,
    padding: '3px 7px',
    fontSize: 12,
    cursor: 'pointer',
  },
  gitBtnPush: {
    background: '#7F77DD',
    color: '#fff',
  },
  gitBusyDot: {
    fontSize: 13,
  },
  branchInputRow: {
    flex: 1,
    display: 'flex',
    gap: 3,
    alignItems: 'center',
    minWidth: 0,
  },
  branchInput: {
    flex: 1,
    minWidth: 0,
    background: 'var(--vscode-input-background)',
    color: 'var(--vscode-input-foreground)',
    border: '1px solid var(--vscode-focusBorder)',
    borderRadius: 3,
    padding: '2px 6px',
    fontSize: 11,
  },
  branchConfirm: {
    background: '#22c55e',
    color: '#fff',
    border: 'none',
    borderRadius: 3,
    padding: '2px 6px',
    fontSize: 11,
    cursor: 'pointer',
  },
  branchCancel: {
    background: 'var(--vscode-button-secondaryBackground)',
    color: 'var(--vscode-button-secondaryForeground)',
    border: 'none',
    borderRadius: 3,
    padding: '2px 6px',
    fontSize: 11,
    cursor: 'pointer',
  },
  noWorkspaceHint: {
    fontSize: 10,
    opacity: 0.45,
    textAlign: 'center' as const,
    padding: '2px 0',
    userSelect: 'none' as const,
  },
}
